// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH inserted AS (
    INSERT INTO feed_follows (id, created_at, updated_at, user_id, feed_id)
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
    RETURNING id, created_at, updated_at, user_id, feed_id
)
SELECT inserted.id, users.name AS user_name, feeds.name AS feed_name 
FROM inserted
JOIN users ON users.id = inserted.user_id
JOIN feeds ON feeds.id = inserted.feed_id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type CreateFeedFollowRow struct {
	ID       uuid.UUID
	UserName string
	FeedName string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i CreateFeedFollowRow
	err := row.Scan(&i.ID, &i.UserName, &i.FeedName)
	return i, err
}

const getFeedFollowings = `-- name: GetFeedFollowings :many
SELECT feed_follows.id, users.name AS user_name, feeds.name AS feed_name 
FROM feed_follows
JOIN users ON users.id = feed_follows.user_id
JOIN feeds ON feeds.id = feed_follows.feed_id
WHERE users.name = $1
`

type GetFeedFollowingsRow struct {
	ID       uuid.UUID
	UserName string
	FeedName string
}

func (q *Queries) GetFeedFollowings(ctx context.Context, name string) ([]GetFeedFollowingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowings, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowingsRow
	for rows.Next() {
		var i GetFeedFollowingsRow
		if err := rows.Scan(&i.ID, &i.UserName, &i.FeedName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
